coverage:
  ignore:
    - "examples/**"
    - "**/*_example.go"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
