run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - misspell
    - gofmt
    - goimports
    - goconst
    - gocritic
    - gocyclo
    - dupl
    - funlen
    - lll

linters-settings:
  goimports:
    local-prefixes: go.rumenx.com/chatbot
  funlen:
    lines: 100
    statements: 50
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 140

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - dupl
        - lll
